<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.git/config</string>
		<string>git/config</string>
		<string>.gitconfig</string>
		<string>etc/gitconfig</string>
		<string>.gitmodules</string>
	</array>
	<key>name</key>
	<string>Git Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-zA-Z0-9_][a-zA-Z0-9_\-]*)\s*=\s*!?"([^"]+)"</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([a-zA-Z0-9_][a-zA-Z0-9_\-]*)\s*=\s*([^;#]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.git-config</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.git-config</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.semi-colon.git-config</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.git-config</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((#).*$\n?)|((;).*$\n?)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.header</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\[([^]"]*("\w+")?)\]</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gitconfig</string>
	<key>uuid</key>
	<string>b2e45ae3-fc3a-49a0-999e-d738695780b8</string>
</dict>
</plist>
