<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.gitignore</string>
	</array>
	<key>name</key>
	<string>Git Ignore</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>[#].*$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gitignore</string>
	<key>uuid</key>
	<string>894b32c4-4aca-4007-817f-adbd10cdb121</string>
</dict>
</plist>
